export default {
  themes: {
    light: {
      colors: {
        'primary': localStorage.getItem('app-preset') || '#794DFF',
        'on-primary': '#fff',
        'secondary': '#6D788D',
        'on-secondary': '#fff',
        'info': '#06b6d4',
        'success': '#02ca4b',
        'on-success': '#fff',
        'warning': '#eab308',
        'on-warning': '#fff',
        'error': '#fb4141',
        'background': '#f8fafc',
        'on-background': '#3F404D',
        'on-surface': '#3F404D',
        'skin-bordered-background': '#fafafa',
        'skin-bordered-surface': '#ffffff',
      },
      variables: {
        'border-color': '#919eab',
        'border-opacity': '0.24',
        'hover-opacity': '0.06',
        'table-header-color': '#696c6f',
        'scrollbar-thumb': '#dbdade',
        'high-emphasis-opacity': '0.9',
        'medium-emphasis-opacity': '0.8',
        'disabled-opacity': 0.4,
        'overlay-scrim-background': '#212b36',
        'overlay-scrim-opacity': 0.5,

        // Shadows
        'shadow-key-umbra-opacity': 'rgba(var(--v-border-color), 0.2)',
        'shadow-key-penumbra-opacity': 'rgba(var(--v-border-color), 0.14)',
        'shadow-key-ambient-opacity': 'rgba(var(--v-border-color), 0.12)',
      },
    },
    dark: {
      colors: {
        'primary': localStorage.getItem('app-preset') || '#794DFF',
        'on-primary': '#fff',
        'secondary': '#6D788D',
        'on-secondary': '#fff',
        'info': '#06b6d4',
        'success': '#02ca4b',
        'warning': '#eab308',
        'on-warning': '#fff',
        'error': '#fb4141',
        'background': '#1a223f',
        'surface': '#212946',
        'on-surface': '#B8B6C0',
        'on-background': '#B8B6C0',
        'skin-bordered-background': '#111827',
        'skin-bordered-surface': '#202a37',
      },
      variables: {
        'border-color': '#CECCD6',
        'border-opacity': '0.1',
        'hover-opacity': '0.06',
        'idle-opacity': '0.04',
        'table-header-color': '#aeb3b7',
        'scrollbar-thumb': '#4a5072',
        'high-emphasis-opacity': '0.9',
        'medium-emphasis-opacity': '0.8',
        'disabled-opacity': 0.4,
        'overlay-scrim-background': '#4a5072',
        'overlay-scrim-opacity': 0.5,

        // Shadows
        'shadow-key-umbra-opacity': 'rgba(0, 0, 0, 0.2)',
        'shadow-key-penumbra-opacity': 'rgba(0, 0, 0, 0.14)',
        'shadow-key-ambient-opacity': 'rgba(0, 0, 0, 0.12)',
      },
    },
  },
}
